### ISSUE TITLE
[IMPORTANT] Security Vulnerability

### ISSUE THREAD

**Issue by Acquized** [Tom7653/ProjectRetile#16]
* Affected Versions: **Any (v1.0.0-PRERELEASEa - v1.0.1)**
* Affected Operating System(s): **Every one that supports SQL-like databases**
* Affected Database(s): **MySQL, SQLite (every version of these two)**
* Reproduceable? **10/10 times**

### Description
> Tom has been notified about this in Spigot PM conversations. Any tries to contact him further than Spigot PM's have not happened (yet!).

A full report containing how to reproduce this bug and what security vulnerability it is has been sent.
 ```
Sent Time: Sun, Jan 8, 2017 at 1:08 AM +01:00
More details at: Sun, Jan 8, 2017 at 1:15 AM +01:00
Even more details at: Sun, Jan 8, 2017 at 2:31 PM +01:00
```
### Suggestions to the community
1. If you have valuable informations on the databases connected to ProjectRetile, then **remove any connections from ProjectRetile to your databases immediantly** and use temporary a SQLite database, a different database server or use another SQLite file.
2. Notify friends who are running ProjectRetile or its forks.

**Comment by WolverinDEV** [comment]
Irre ich mich oder handelt es sich um SQL injection?
Wenn ja: https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet#Oracle_Escaping
Ganz einfach in der SQL klasse nutzen
